services:
  - type: web
    name: canteen-website
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn canteen_website.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: canteen_website.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: ALLOWED_HOSTS
        value: your-site-name.onrender.com
